version: '3.2'

services:
  db:
    image: mariadb
    restart: always
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_USER=friendica
      - MYSQL_PASSWORD=friendica
      - MYSQL_DATABASE=friendica
      - MYSQL_RANDOM_ROOT_PASSWORD=yes

  app:
    image: friendica/server
    restart: always
    ports:
      - 8080:80
    volumes:
      - friendica:/var/www/html
    environment:
      - AUTOINSTALL=true
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
      - MYSQL_USER=friendica
      - MYSQL_PASSWORD=friendica
      - MYSQL_DATABASE=friendica
      - MAILNAME=root@friendica.local
    hostname: friendica.local
    depends_on:
      - db

  cron:
    image: friendica/server
    restart: always
    volumes:
      - friendica:/var/www/html
    entrypoint: /cron.sh
    environment:
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
      - MYSQL_USER=friendica
      - MYSQL_PASSWORD=friendica
      - MYSQL_DATABASE=friendica
      - MAILNAME=root@friendica.local
    depends_on:
      - db

volumes:
  db:
  friendica: